### ISSUE TITLE
1.3.0.1 seems to be an invalid version pattern for npm

### ISSUE THREAD

**Issue by dhritzkiv** [owenmead/Pikaday#12]
I think npm is very particular about the version number patterns, and 1.3.0.1 doesn't fit semver, resulting in the error "Invalid version"

Could the version be bumped to 1.3.1?

**Comment by owenmead** [comment]
This was my screw up. Still learning. Wanting to track with regular Pikaday
so waiting a but till 1.3.1 then will do another release. Maybe aligning
versions is unnecessary.

**Comment by owenmead** [comment]
Just updated to 1.3.2 so should be good to go now
