### ISSUE TITLE
Error to change select.

### ISSUE THREAD

**Issue by dixso** [owenmead/Pikaday#13]
Hi,
In this new version you can't select nothing.
The problem is here:
https://github.com/owenmead/Pikaday/blob/master/pikaday.js#L462
If you remove this line working properly.

I don't know why this line...
https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L408

Regards!

**Comment by lukemadera** [comment]
Firstly, awesome time picker @owenmead !

+1 - the time picker seems unusable currently.
On Ubuntu Linux and Firefox, if I right click first to give the time picker select focus, then I can select (left click as normal) but I have to first right click before it will work.
On Windows 7 (Firefox & Chrome) and Ubuntu Chrome, the time picker does not work at all.

Any time estimate on a fix as this is obviously a major bug - @dixso may be right it's simply commenting out the preventDefault line?

**Comment by cmroberts** [comment]
+2 the time picker isn't usable without dixso's modification. Commenting line 462 has worked for me without introducing any obvious issues, but I'll second the up vote for a more complete fix if there is one.

**Comment by owenmead** [comment]
Good catch. Sloppy of me not to manually test it before pushing version out. It was a simple merge with upstream so I thought I was safe.

Will find out why the preventDefault was there in the first place, and try to maintain that idea while getting the time selectors working again.

**Comment by owenmead** [comment]
Due to https://github.com/dbushell/Pikaday/issues/249 I didn't simply comment out the line. Instead do not preventDefault when trying to select time.

Will version bump.

**Comment by cmroberts** [comment]
Thanks, @owenmead! The new fix works great.

**Comment by lukemadera** [comment]
Thanks @owenmead !

**Comment by jkleinsc** [comment]
@owenmead It looks like dbushell#249 was rolled back because it because it breaks the month and year dropdown.
