### ISSUE TITLE
Seems that clicking the month or year to change them is broken

### ISSUE THREAD

**Issue by rwwagner90** [owenmead/Pikaday#16]
See on this plnkr here:
http://plnkr.co/edit/bKU2SwyTDwgBG4XC3bxk?p=preview

**Comment by owenmead** [comment]
Yep, that `preventDefault` line caused more issues then breaking the time pickers. I have since merged master from upstream dbushell, and removed the guard code I introduced as a result of that problem line. All pushed into master now.

**Comment by kushdilip** [comment]
@owenmead When are going to release this bug fix.

**Comment by owenmead** [comment]
Quite certain this has been released

**Comment by kushdilip** [comment]
Cool :+1:
