### ISSUE TITLE
Pikaday-time closes before you can set the time

### ISSUE THREAD

**Issue by alexbain** [owenmead/Pikaday#17]
Thanks for the fork that adds time support. 

One thing I'm noticing is that the datepicker closes before the user is able to set the time if they select a date first.

Reproduction steps:

* Open Pikaday-time datepicker
* Select date
* Pikaday-time datepicker automatically closes
* Open Pikaday-time datepicker a second time
* Select time
* Pikaday-time datepicker does not automatically close
* Click outside of datepicker to close it

I think it would be useful if Pikaday-time stayed open until a user has a chance to select both a date and a time.

**Comment by owenmead** [comment]
One option would be to disable the "close on select date" such that the picker stays open until the user explicitly closes it. Not sure the best UI flow. Suggestions?

**Comment by alexbain** [comment]
Ah, I didn't realize that option existed. That fixes my immediate issue - as long as the user has an option to enter both a date and time before the pop up closes I think the UI flow is fine.

As an improvement suggestion, a "close on select time" option would be a nice addition. That way you could dial in the behavior you want.

Either ways, that improvement can be tracked separately from this issue. Closing.

**Comment by owenmead** [comment]
Could you please create a new issue to track close on select time please?
Looks to be a good solution.

Setting up sane defaults along with these will go a long way

**Comment by alexbain** [comment]
https://github.com/owenmead/Pikaday/issues/18

**Comment by ctcpip** [comment]
@owenmead  - You said 'disable the "close on select date"'.  I don't see this option.

**Comment by owenmead** [comment]
PR Merged
