### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by mhkeller** [owenmead/Pikaday#19]
It doesn't seem that the dropdown times reflect the timezone (if using moment) but rather default to the user's timezone. I put through a very rough, quick fix here but it would be nice if this were worked out in a more consistent and robust way: https://github.com/newslynx/Pikaday/commit/9f961db9efd615b778b54be80adff329a99f4622

**Comment by owenmead** [comment]
Overall like the idea of timezone and better i18n support. Comments added inline with your commit.

Perhaps you could put together a pull request for this?

**Comment by mhkeller** [comment]
I'm not super knowledgeable about the internals so it might not be the most elegant but what I can do is when I'm done with our current project release I'll refine that existing fork as best I find and see how it goes. In the meantime if you have any thoughts don't let me get in the way. I'll post here with any updates.

**Comment by owenmead** [comment]
All good, I'm happy to help with Pikaday internals and such. Probably best to follow the pattern of turning time on/off and do the same for timezone. Should work without having to specify any timezone or i18n configs.

**Comment by mhkeller** [comment]
hmm how would it work without specifying a timezone? For instance, if a
user is at an organization in Eastern time but they are traveling in
Pacific time. When they log in they want to make sure all dates and times
are displayed in Eastern format even though the datetime stamps are in UTC.

On Mon, Jun 22, 2015 at 3:52 PM, Owen Mead-Robins <notifications@github.com>
wrote:

> All good, I'm happy to help with Pikaday internals and such. Probably best
> to follow the pattern of turning time on/off and do the same for timezone.
> Should work without having to specify any timezone or i18n configs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owenmead/Pikaday/issues/19#issuecomment-114237193>.
>



-- 
@mhkeller
mhkeller.com

**Comment by owenmead** [comment]
By not specifying timezone, it would be timezone naive. We shouldn't force
a user to specify a timezone if they don't have to deal with timezones.
What if I'm building an app for an organization that never has to deal with
timezones?

**Comment by mhkeller** [comment]
I see. I thought you mean "It should work" in that it should somehow detect a timezone and "work" in that sense. Yes I agree it should be optional.

**Comment by owenmead** [comment]
Looks to be solved. Reopen or create a new issue of not solved. Thanks.
