### ISSUE TITLE
Wonky positioning

### ISSUE THREAD

**Issue by rmcauley** [owenmead/Pikaday#21]
I've dropped in ownmead/Pikaday to add time selection over dbushell/Pikaday, but the Pikaday window appears in entirely the wrong place.  dbushell's appears in the correct space, but the current version here appears at left: -540px on my space.

This commit seems to be the one that fixes things for me if I start replacing Javascript: https://github.com/dbushell/Pikaday/commit/6ec802ca189a3c1830465308123a7d93bd6cdad1

**Comment by vandry** [comment]
I have the same issue (mine appeared at -468px) and I worked around it without changing Pikaday code by specifying `reposition: false` in the options.

**Comment by owenmead** [comment]
I've merged in upstream which should correct this issue.

**Comment by rmcauley** [comment]
Thanks a lot! :)

**Comment by owenmead** [comment]
So confirmed that the problem is solved on your end as well with the new version?

**Comment by rmcauley** [comment]
Not confirmed, no, project is in a "it is working and I don't want to touch it" state. :)  However since you've pulled in the fix for it from upstream I'm happy to keep this closed and assume it works!
