### ISSUE TITLE
`minDate` is a day later when showing time

### ISSUE THREAD

**Issue by Calvein** [owenmead/Pikaday#32]
I edited the example to have the same options, with the exception of `showTime` that is false for the first one and true for the next one.

The code for both:
```js
<script>

var picker = new Pikaday(
{
    field: document.getElementById('datepicker'),
    firstDay: 1,
    minDate: new Date(),
    showTime: false,
});

var timepicker = new Pikaday(
{
    field: document.getElementById('datetimepicker'),
    firstDay: 1,
    minDate: new Date(),
    showTime: true
});

</script>
```

And the result:
![image](https://cloud.githubusercontent.com/assets/243189/13237660/bac4d90a-da21-11e5-9b2d-5399b8f26288.png)

**Comment by owenmead** [comment]
Yep, it's a bug with the time branch. Had 20min before I had run out but couldn't find the true source. PR appreciated. Will see if I can get to fixing it.

**Comment by owenmead** [comment]
Work looks to be ramping up again for me, so might not get to this for a little while. Will find time to review a PR though if someone wants to take this on.

**Comment by dzoltok** [comment]
This looks to be an issue with maxDate as well; I'm trying to specify a datetime range, and it looks like when the end date is picked and the onSelect function tries to set the maxDate on the start date, I'm unable to pick any time other than midnight. I'll try to figure out the correct handling, if you have any ideas from your initial look I'd appreciate them!

**Comment by owenmead** [comment]
It's been a month since I looked at it, but found something similar, in that it is tied to the maxDate and there are some subtitles that need to be taken into account. I have seen some fixes come in upstream, but was waiting to merge them in until they did a release. Probably a good idea to look at those.

Would appreciate a PR if you can fix this. Thanks @dzoltok !

**Comment by dzoltok** [comment]
Submitted a small fix that solved the problem for me.

**Comment by sashamjolnir** [comment]
any progress on this?

**Comment by owenmead** [comment]
PR from @dzoltok merged in fixes this. Thanks @dzoltok
