### ISSUE TITLE
Multiple pickdays get the old hour on open

### ISSUE THREAD

**Issue by mfandre** [owenmead/Pikaday#40]
At method "show" I alter the code to:

`show: function () {
            if (!this._v) {
                removeClass(this.el, 'is-hidden');
                this._v = true;
//alter for clear the hour select box 
                if (this._o.field.value == '') {
                    this._d = new Date();
                    this._d.setHours(0);
                    this._d.setMinutes(0);
                }
                this.draw();
                if (this._o.bound) {
                    addEvent(document, 'click', this._onClick);
                    this.adjustPosition();
                }
                if (typeof this._o.onOpen === 'function') {
                    this._o.onOpen.call(this);
                }
            }
},`

**Comment by owenmead** [comment]
Bit of cleanup
