### ISSUE TITLE
Custom format?

### ISSUE THREAD

**Issue by Manish-Kr09** [owenmead/Pikaday#42]
Can we format date and time string to use this control for reminder. 
reminder Sat June18, 2016 at 8:06:00 AM.

With time i am stick to use 1 format. Can we?

**Comment by bonnici** [comment]
This is possible if you use the moment.js integration, but I couldn't get the custom toString function to work.

**Comment by Manish-Kr09** [comment]
@bonnici, 

Thanks for your response. Though it's quite old ;) 

I have resolved that by overriding toString method. 
`toString: function(format) {
            return !isDate(this._d) ? '' : hasMoment ? moment(this._d).format(format || this._o.format) : this._o.showTime ? Ext.Date.format(this._d, 'M j, Y \\a\\t h:i A') : Ext.Date.format(this._d, 'M j, Y');
        },`

**Comment by owenmead** [comment]
You can pass a custom function to `toString` option if you want. That is probably what you want.
