### ISSUE TITLE
Set min-max Time

### ISSUE THREAD

**Issue by rolandtoth** [owenmead/Pikaday#43]
Is there a way to set the min-max time? For example, I have a form that would accept only working hours, .e.g 8:00 - 18:00. 

Optimally the visitors would be able to choose from this time range, and the default time woudl be set to the starting hour.

**Comment by owenmead** [comment]
Currently not a way to set "working hours" as you've described. A PR would
be great for it as that could be really useful.

**Comment by rolandtoth** [comment]
I started to implement it and it's partially done, I'll come back when it's ready.

**Comment by owenmead** [comment]
Great, thanks :)

**Comment by mattheworres** [comment]
@rolandtoth how far did you get on a PR for this? Thanks!

**Comment by rolandtoth** [comment]
Not much, only works one-way so far because I haven't had the time to investigate.
If one manually enters a time off range it doesn't auto-correct it.

**Comment by owenmead** [comment]
closing to cleanup. If you make progress etc. feel free to reopen.
