### ISSUE TITLE
Correct Time-Format for php/mysql in value

### ISSUE THREAD

**Issue by pestKater** [owenmead/Pikaday#46]
Hey there. I just found your Extension. Great job. But:
If I picked a Date with Time I get sth. like this: 
`string(65) "Sat Aug 13 2016 18:00:00 GMT+0200 (Mitteleurop??ische Sommerzeit)"`

Now I want to write my picked date and time in the database. Do I really need to substr the output? Or can I use the format I want to?

**Comment by owenmead** [comment]
Main documentation is best bet:
https://github.com/dbushell/Pikaday

You probably want `picker.toString('YYYY-MM-DD')` and better if you use
Moment. Follow the Moment docs for formatting the string.
