### ISSUE TITLE
Getting runtime Error: "Pikaday is not defined" after "jspm install"

### ISSUE THREAD

**Issue by arjyamishra** [owenmead/Pikaday#48]
I have installed the library through **jspm**: [https://www.npmjs.com/package/pikaday-time]

> jspm install npm:pikaday-time

and using in my code as: 

```
import "pikaday-time";
....
picker = new Pikaday({
            field: ..... ,
            onSelect: () => {.... },
            onOpen: () => {.... },
            showTime: true
        });

....
```

Run time Error: **"Pikaday is not defined"** 
![pikaday-time_error](https://cloud.githubusercontent.com/assets/17160229/18051503/3270c8da-6df5-11e6-8b0c-b65f81ce0daf.PNG)

Then I check the library **dbushell/Pikaday** and found that below 2 lines are present in file: **pikaday@1.4.0/pikaday.js** after installation

> "format global";
> "deps ./css/pikaday.css!";

So, after adding above 2 lines in installed file: **pikaday-time@1.4.1/pikaday.js**  in place of 

> "format cjs";

 everything seems to be working fine.

Kindly let me know if I am doing anything wrong or is there any problem with the installation or usage in the code.

**Comment by Sayan751** [comment]
Facing the same issue with webapck. I am using `var Pikaday = require("pikaday");` to load the Pikaday, which openup the control but missing the styles.

**Comment by owenmead** [comment]
import Pikaday from 'pikaday-time';
