### ISSUE TITLE
Could you merge in 1.5.1?

### ISSUE THREAD

**Issue by Leeds-eBooks** [owenmead/Pikaday#51]
`dbushell` has released [`1.5.1`](https://github.com/dbushell/Pikaday/releases/tag/1.5.1) to fix https://github.com/dbushell/Pikaday/issues/598. Any chance you could merge this in? Thanks!

**Comment by Leeds-eBooks** [comment]
This would also close #47

**Comment by owenmead** [comment]
1.5.1 merged and published

**Comment by Leeds-eBooks** [comment]
Fantastic, thanks very much!
