### ISSUE TITLE
how to disable time collection for fields that are Date only

### ISSUE THREAD

**Issue by memoht** [owenmead/Pikaday#53]
I replaced my standard `Pikaday` with this fork and I like the implementation, but I have several fields in forms that are `Date` only, not `DateTime`. I tried to implement the options for turning off Hour and Minutes in specific fields, but they are still showing up everywhere.
Is it not possible to selectively disable the Hour and Time functions?

**Comment by vpatil** [comment]
@memoht Setting the `showTime` prop to `false` hid the time picker for me.

**Comment by memoht** [comment]
@vpatil Do you perhaps have an example? Maybe my syntax isn't correct. Here is an example from from a `.coffee` file in my app.
```
  picker = new Pikaday(field: document.getElementById('task_due_date'),
    firstDay: 1, disableWeekends: true, showTime: false)
```

**Comment by memoht** [comment]
Amended. I tried the alternate syntax for jQuery and it worked.
```
  picker = new Pikaday(field: $("#task_due_date")[0],
  firstDay: 1, disableWeekends: true, showTime: true)
```
Thanks. I will proceed with this.
