### ISSUE TITLE
Set default time?

### ISSUE THREAD

**Issue by kvanlaan** [owenmead/Pikaday#54]
Hi, currently the time picker just sets midnight as the default time. How can I change this? Thanks!

**Comment by AlexeyMK** [comment]
seems like the one open pull request has this feature - any chance we could get that part merged?

**Comment by AlexeyMK** [comment]
seems like we can use defaultDate here? https://github.com/owenmead/Pikaday/pull/38

**Comment by kvanlaan** [comment]
Thanks!
