### ISSUE TITLE
Add latest commits from original package

### ISSUE THREAD

**Issue by arthurkirkosa** [owenmead/Pikaday#55]
Will this ever happen? :D

Thanks

**Comment by owenmead** [comment]
Just merged upstream. Please try and do a second pass to ensure no new issues were introduced. Will push to NPM etc. after

**Comment by arthurkirkosa** [comment]
I think it's ok to tag a new release

**Comment by owenmead** [comment]
Github Tagged and published to NPM

**Comment by arthurkirkosa** [comment]
Upgraded and can confirm it's working
