### ISSUE TITLE
incrementMinuteBy not working

### ISSUE THREAD

**Issue by log69** [owenmead/Pikaday#58]
Hi Owen, thanks for this nice code. I can't seem to make incrementMinuteBy working. I specify incrementMinuteBy: 5 or any other values and the increment remains 1 showing minutes form 0 to 59 stepping 1.

Could you kindly help? Thx.

**Comment by owenmead** [comment]
Thanks for the feedback. I'm no longer maintaining this code. Happy to point this repo to yours if you would like to carry the torch from here.
