### ISSUE TITLE
onSelect not called when choosing already selected value

### ISSUE THREAD

**Issue by SimonThordal** [owenmead/Pikaday#59]
When selecting the initially chosen time from the timepicker it seems as though `onSelect` isn't firing. This is a problem because Timepicker does not seem to use the value of the `defaultDate` passed to Pikaday to set the initial time, instead falling back on the first whole hour, so if the `defaultDate` is 10:33 for instance, the initially set time is 10:00. It is then impossible to actually select 10:00 for the user since no `onSelect` will fire.

Possible fix could be to fire `onSelect` even if the chosen time is the same as the previous time.

**Comment by owenmead** [comment]
Thanks for the feedback. I'm no longer maintaining this code. Happy to point this repo to yours if you would like to carry the torch from here.
