### ISSUE TITLE
Time selector positioning defect in Firefox

### ISSUE THREAD

**Issue by mtmacdonald** [owenmead/Pikaday#6]
In Firefox 34.0 on Ubuntu 14.04 I'm seeing a positioning defect where the time selectors appear outside the datepicker container (see screenshot).

![pikaday-defect-firefox](https://cloud.githubusercontent.com/assets/2428859/5539196/c45001b0-8abe-11e4-95e1-3500bf0d48cf.png)

**Comment by owenmead** [comment]
A PR would be great with the needed CSS updates.

**Comment by owenmead** [comment]
@billyvg patch fixed this, and now merged into master.

Tested on FF 35.0.1
