### ISSUE TITLE
Handling minutes and seconds in setMinDate 

### ISSUE THREAD

**Issue by voronianski** [owenmead/Pikaday#7]
It's needed for `setMinDate` to handle minutes (and seconds too). 

For example when setting `minDate` to `'2014-12-24 13:00:00'` it colors the whole day of **24.12** as disabled.

<img src="https://dl.dropboxusercontent.com/u/100463011/pikaday-minutes-mindate.png" width="300">

**Comment by owenmead** [comment]
Would you mind doing a PR for this?

**Comment by owenmead** [comment]
I've done a basic fix such that the days will be clickable again. However, I haven't changed the dropdowns to support the time portions of min/max date.

Would appreciate a PR to solve the time picking supporting min/max when time is specified. Closing this as a "good enough" fix
